name: Data Integration Automation

on:
  push:
    paths:
      - "incoming-data/**"  # Trigger workflow if files in the incoming-data folder are updated
      - "data-hub/**"  # Trigger workflow when files in the data-hub folder are updated

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run the Bash script
      - name: Run data integration script
        run: |
          bash scripts/integrate.sh

      # Step 3: Commit and push the updated integrated file
      - name: Commit and push updates
        run: |
          git config user.name "Onifade Michael"
          git config user.email "themichaelonifade@gmail.com"
          git add db/integrated_data.csv
          git commit -m "Automated update of integrated_data.csv"
          git push
